# -*- mode: ruby -*-
# vi: set ft=ruby :


# Require YAML module
require 'yaml'

# Read YAML file with box details
nodes = YAML.load_file('nodes.yaml')


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu"

  nodes.each do |node|
    config.vm.define node["name"] do |machine|
      machine.vm.box = node["box"]
      machine.vm.network "private_network", ip: node["ip"]
      machine.vm.provider :virtualbox do |vb|
        vb.name = node["name"]
        vb.memory = node["ram"]
      end
      machine.vm.provision :shell, path: "bootstrap-node.sh"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
